export enum Role {
  ADMIN = 'ADMIN',
  PMO = 'PMO',
  COORDINADOR = 'COORDINADOR',
  SCRUM_MASTER = 'SCRUM_MASTER',
  PATROCINADOR = 'PATROCINADOR',
  DESARROLLADOR = 'DESARROLLADOR',
  IMPLEMENTADOR = 'IMPLEMENTADOR',
}

export const ROLE_HIERARCHY = {
  [Role.ADMIN]: 100,
  [Role.PMO]: 90,
  [Role.COORDINADOR]: 80,
  [Role.SCRUM_MASTER]: 70,
  [Role.PATROCINADOR]: 60,
  [Role.DESARROLLADOR]: 50,
  [Role.IMPLEMENTADOR]: 50,
};
